//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the limo_application package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __limo_application__CROSSWALKCONFIG_H__
#define __limo_application__CROSSWALKCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace limo_application
{
  class crosswalkConfigStatics;

  class crosswalkConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(crosswalkConfig &config, const crosswalkConfig &max, const crosswalkConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const crosswalkConfig &config1, const crosswalkConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, crosswalkConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const crosswalkConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, crosswalkConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const crosswalkConfig &config) const = 0;
      virtual void getValue(const crosswalkConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T crosswalkConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T crosswalkConfig::* field;

      virtual void clamp(crosswalkConfig &config, const crosswalkConfig &max, const crosswalkConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const crosswalkConfig &config1, const crosswalkConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, crosswalkConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const crosswalkConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, crosswalkConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const crosswalkConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const crosswalkConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, crosswalkConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, crosswalkConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<crosswalkConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(crosswalkConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class CROSSWALK_DETECTION
{
  public:
    CROSSWALK_DETECTION()
    {
      state = true;
      name = "CrossWalk_Detection";
    }

    void setParams(crosswalkConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("white_h_low"==(*_i)->name){white_h_low = boost::any_cast<int>(val);}
        if("white_h_high"==(*_i)->name){white_h_high = boost::any_cast<int>(val);}
        if("white_l_low"==(*_i)->name){white_l_low = boost::any_cast<int>(val);}
        if("white_l_high"==(*_i)->name){white_l_high = boost::any_cast<int>(val);}
        if("white_s_low"==(*_i)->name){white_s_low = boost::any_cast<int>(val);}
        if("white_s_high"==(*_i)->name){white_s_high = boost::any_cast<int>(val);}
        if("rho"==(*_i)->name){rho = boost::any_cast<int>(val);}
        if("theta"==(*_i)->name){theta = boost::any_cast<int>(val);}
        if("threshold"==(*_i)->name){threshold = boost::any_cast<int>(val);}
        if("crosswalk_detect_threshold"==(*_i)->name){crosswalk_detect_threshold = boost::any_cast<int>(val);}
      }
    }

    int white_h_low;
int white_h_high;
int white_l_low;
int white_l_high;
int white_s_low;
int white_s_high;
int rho;
int theta;
int threshold;
int crosswalk_detect_threshold;

    bool state;
    std::string name;

    
}crosswalk_detection;

}groups;



//#line 24 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int white_h_low;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int white_h_high;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int white_l_low;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int white_l_high;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int white_s_low;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int white_s_high;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int rho;
//#line 31 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int theta;
//#line 32 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int threshold;
//#line 33 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      int crosswalk_detect_threshold;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("crosswalkConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const crosswalkConfig &__max__ = __getMax__();
      const crosswalkConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const crosswalkConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const crosswalkConfig &__getDefault__();
    static const crosswalkConfig &__getMax__();
    static const crosswalkConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const crosswalkConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void crosswalkConfig::ParamDescription<std::string>::clamp(crosswalkConfig &config, const crosswalkConfig &max, const crosswalkConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class crosswalkConfigStatics
  {
    friend class crosswalkConfig;

    crosswalkConfigStatics()
    {
crosswalkConfig::GroupDescription<crosswalkConfig::DEFAULT, crosswalkConfig> Default("Default", "", 0, 0, true, &crosswalkConfig::groups);
crosswalkConfig::GroupDescription<crosswalkConfig::DEFAULT::CROSSWALK_DETECTION, crosswalkConfig::DEFAULT> CrossWalk_Detection("CrossWalk_Detection", "", 0, 1, true, &crosswalkConfig::DEFAULT::crosswalk_detection);
//#line 24 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.white_h_low = 0;
//#line 24 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.white_h_low = 255;
//#line 24 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.white_h_low = 50;
//#line 24 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_h_low", "int", 10, "H Channel Low threshold", "", &crosswalkConfig::white_h_low)));
//#line 24 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_h_low", "int", 10, "H Channel Low threshold", "", &crosswalkConfig::white_h_low)));
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.white_h_high = 0;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.white_h_high = 255;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.white_h_high = 50;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_h_high", "int", 11, "H Channel High threshold", "", &crosswalkConfig::white_h_high)));
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_h_high", "int", 11, "H Channel High threshold", "", &crosswalkConfig::white_h_high)));
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.white_l_low = 0;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.white_l_low = 255;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.white_l_low = 50;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_l_low", "int", 12, "L ChannelLow threshold", "", &crosswalkConfig::white_l_low)));
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_l_low", "int", 12, "L ChannelLow threshold", "", &crosswalkConfig::white_l_low)));
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.white_l_high = 0;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.white_l_high = 255;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.white_l_high = 50;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_l_high", "int", 13, "L Channel High threshold", "", &crosswalkConfig::white_l_high)));
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_l_high", "int", 13, "L Channel High threshold", "", &crosswalkConfig::white_l_high)));
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.white_s_low = 0;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.white_s_low = 255;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.white_s_low = 50;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_s_low", "int", 14, "S Channel Low threshold", "", &crosswalkConfig::white_s_low)));
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_s_low", "int", 14, "S Channel Low threshold", "", &crosswalkConfig::white_s_low)));
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.white_s_high = 0;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.white_s_high = 255;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.white_s_high = 50;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_s_high", "int", 15, "S Channel High threshold", "", &crosswalkConfig::white_s_high)));
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("white_s_high", "int", 15, "S Channel High threshold", "", &crosswalkConfig::white_s_high)));
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.rho = 1;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.rho = 255;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.rho = 1;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("rho", "int", 16, "Hough rho", "", &crosswalkConfig::rho)));
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("rho", "int", 16, "Hough rho", "", &crosswalkConfig::rho)));
//#line 31 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.theta = 0;
//#line 31 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.theta = 255;
//#line 31 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.theta = 0;
//#line 31 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("theta", "int", 17, "Hough theta", "", &crosswalkConfig::theta)));
//#line 31 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("theta", "int", 17, "Hough theta", "", &crosswalkConfig::theta)));
//#line 32 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.threshold = 1;
//#line 32 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.threshold = 255;
//#line 32 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.threshold = 1;
//#line 32 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("threshold", "int", 18, "Hough threshold", "", &crosswalkConfig::threshold)));
//#line 32 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("threshold", "int", 18, "Hough threshold", "", &crosswalkConfig::threshold)));
//#line 33 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __min__.crosswalk_detect_threshold = 1;
//#line 33 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __max__.crosswalk_detect_threshold = 1000;
//#line 33 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __default__.crosswalk_detect_threshold = 15;
//#line 33 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      CrossWalk_Detection.abstract_parameters.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("crosswalk_detect_threshold", "int", 19, "More lines detected over this value, it will be detected as crosswalk", "", &crosswalkConfig::crosswalk_detect_threshold)));
//#line 33 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/crosswalk.cfg"
      __param_descriptions__.push_back(crosswalkConfig::AbstractParamDescriptionConstPtr(new crosswalkConfig::ParamDescription<int>("crosswalk_detect_threshold", "int", 19, "More lines detected over this value, it will be detected as crosswalk", "", &crosswalkConfig::crosswalk_detect_threshold)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      CrossWalk_Detection.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(crosswalkConfig::AbstractGroupDescriptionConstPtr(new crosswalkConfig::GroupDescription<crosswalkConfig::DEFAULT::CROSSWALK_DETECTION, crosswalkConfig::DEFAULT>(CrossWalk_Detection)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(crosswalkConfig::AbstractGroupDescriptionConstPtr(new crosswalkConfig::GroupDescription<crosswalkConfig::DEFAULT::CROSSWALK_DETECTION, crosswalkConfig::DEFAULT>(CrossWalk_Detection)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(crosswalkConfig::AbstractGroupDescriptionConstPtr(new crosswalkConfig::GroupDescription<crosswalkConfig::DEFAULT, crosswalkConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<crosswalkConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<crosswalkConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<crosswalkConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    crosswalkConfig __max__;
    crosswalkConfig __min__;
    crosswalkConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const crosswalkConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static crosswalkConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &crosswalkConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const crosswalkConfig &crosswalkConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const crosswalkConfig &crosswalkConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const crosswalkConfig &crosswalkConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<crosswalkConfig::AbstractParamDescriptionConstPtr> &crosswalkConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<crosswalkConfig::AbstractGroupDescriptionConstPtr> &crosswalkConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const crosswalkConfigStatics *crosswalkConfig::__get_statics__()
  {
    const static crosswalkConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = crosswalkConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CROSSWALKRECONFIGURATOR_H__
