//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the limo_application package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __limo_application__IMAGE_PROCESSINGCONFIG_H__
#define __limo_application__IMAGE_PROCESSINGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace limo_application
{
  class image_processingConfigStatics;

  class image_processingConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(image_processingConfig &config, const image_processingConfig &max, const image_processingConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const image_processingConfig &config1, const image_processingConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, image_processingConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const image_processingConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, image_processingConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const image_processingConfig &config) const = 0;
      virtual void getValue(const image_processingConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T image_processingConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T image_processingConfig::* field;

      virtual void clamp(image_processingConfig &config, const image_processingConfig &max, const image_processingConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const image_processingConfig &config1, const image_processingConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, image_processingConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const image_processingConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, image_processingConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const image_processingConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const image_processingConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, image_processingConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, image_processingConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<image_processingConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(image_processingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class YELLOW_LANE_DETECTION
{
  public:
    YELLOW_LANE_DETECTION()
    {
      state = true;
      name = "Yellow_Lane_Detection";
    }

    void setParams(image_processingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("yellow_h_low"==(*_i)->name){yellow_h_low = boost::any_cast<int>(val);}
        if("yellow_h_high"==(*_i)->name){yellow_h_high = boost::any_cast<int>(val);}
        if("yellow_l_low"==(*_i)->name){yellow_l_low = boost::any_cast<int>(val);}
        if("yellow_l_high"==(*_i)->name){yellow_l_high = boost::any_cast<int>(val);}
        if("yellow_s_low"==(*_i)->name){yellow_s_low = boost::any_cast<int>(val);}
        if("yellow_s_high"==(*_i)->name){yellow_s_high = boost::any_cast<int>(val);}
      }
    }

    int yellow_h_low;
int yellow_h_high;
int yellow_l_low;
int yellow_l_high;
int yellow_s_low;
int yellow_s_high;

    bool state;
    std::string name;

    
}yellow_lane_detection;

}groups;



//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      int yellow_h_low;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      int yellow_h_high;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      int yellow_l_low;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      int yellow_l_high;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      int yellow_s_low;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      int yellow_s_high;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("image_processingConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const image_processingConfig &__max__ = __getMax__();
      const image_processingConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const image_processingConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const image_processingConfig &__getDefault__();
    static const image_processingConfig &__getMax__();
    static const image_processingConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const image_processingConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void image_processingConfig::ParamDescription<std::string>::clamp(image_processingConfig &config, const image_processingConfig &max, const image_processingConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class image_processingConfigStatics
  {
    friend class image_processingConfig;

    image_processingConfigStatics()
    {
image_processingConfig::GroupDescription<image_processingConfig::DEFAULT, image_processingConfig> Default("Default", "", 0, 0, true, &image_processingConfig::groups);
image_processingConfig::GroupDescription<image_processingConfig::DEFAULT::YELLOW_LANE_DETECTION, image_processingConfig::DEFAULT> Yellow_Lane_Detection("Yellow_Lane_Detection", "", 0, 1, true, &image_processingConfig::DEFAULT::yellow_lane_detection);
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __min__.yellow_h_low = 0;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __max__.yellow_h_low = 255;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __default__.yellow_h_low = 50;
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      Yellow_Lane_Detection.abstract_parameters.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_h_low", "int", 4, "H Channel Low threshold", "", &image_processingConfig::yellow_h_low)));
//#line 25 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __param_descriptions__.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_h_low", "int", 4, "H Channel Low threshold", "", &image_processingConfig::yellow_h_low)));
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __min__.yellow_h_high = 0;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __max__.yellow_h_high = 255;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __default__.yellow_h_high = 50;
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      Yellow_Lane_Detection.abstract_parameters.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_h_high", "int", 5, "H Channel High threshold", "", &image_processingConfig::yellow_h_high)));
//#line 26 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __param_descriptions__.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_h_high", "int", 5, "H Channel High threshold", "", &image_processingConfig::yellow_h_high)));
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __min__.yellow_l_low = 0;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __max__.yellow_l_low = 255;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __default__.yellow_l_low = 50;
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      Yellow_Lane_Detection.abstract_parameters.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_l_low", "int", 6, "L ChannelLow threshold", "", &image_processingConfig::yellow_l_low)));
//#line 27 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __param_descriptions__.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_l_low", "int", 6, "L ChannelLow threshold", "", &image_processingConfig::yellow_l_low)));
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __min__.yellow_l_high = 0;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __max__.yellow_l_high = 255;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __default__.yellow_l_high = 50;
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      Yellow_Lane_Detection.abstract_parameters.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_l_high", "int", 7, "L Channel High threshold", "", &image_processingConfig::yellow_l_high)));
//#line 28 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __param_descriptions__.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_l_high", "int", 7, "L Channel High threshold", "", &image_processingConfig::yellow_l_high)));
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __min__.yellow_s_low = 0;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __max__.yellow_s_low = 255;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __default__.yellow_s_low = 50;
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      Yellow_Lane_Detection.abstract_parameters.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_s_low", "int", 8, "S Channel Low threshold", "", &image_processingConfig::yellow_s_low)));
//#line 29 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __param_descriptions__.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_s_low", "int", 8, "S Channel Low threshold", "", &image_processingConfig::yellow_s_low)));
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __min__.yellow_s_high = 0;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __max__.yellow_s_high = 255;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __default__.yellow_s_high = 50;
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      Yellow_Lane_Detection.abstract_parameters.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_s_high", "int", 9, "S Channel High threshold", "", &image_processingConfig::yellow_s_high)));
//#line 30 "/home/agilex/limo_project/src/limo_legend/cfg/lane_detection/image_processing.cfg"
      __param_descriptions__.push_back(image_processingConfig::AbstractParamDescriptionConstPtr(new image_processingConfig::ParamDescription<int>("yellow_s_high", "int", 9, "S Channel High threshold", "", &image_processingConfig::yellow_s_high)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Yellow_Lane_Detection.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(image_processingConfig::AbstractGroupDescriptionConstPtr(new image_processingConfig::GroupDescription<image_processingConfig::DEFAULT::YELLOW_LANE_DETECTION, image_processingConfig::DEFAULT>(Yellow_Lane_Detection)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(image_processingConfig::AbstractGroupDescriptionConstPtr(new image_processingConfig::GroupDescription<image_processingConfig::DEFAULT::YELLOW_LANE_DETECTION, image_processingConfig::DEFAULT>(Yellow_Lane_Detection)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(image_processingConfig::AbstractGroupDescriptionConstPtr(new image_processingConfig::GroupDescription<image_processingConfig::DEFAULT, image_processingConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<image_processingConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<image_processingConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<image_processingConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    image_processingConfig __max__;
    image_processingConfig __min__;
    image_processingConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const image_processingConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static image_processingConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &image_processingConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const image_processingConfig &image_processingConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const image_processingConfig &image_processingConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const image_processingConfig &image_processingConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<image_processingConfig::AbstractParamDescriptionConstPtr> &image_processingConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<image_processingConfig::AbstractGroupDescriptionConstPtr> &image_processingConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const image_processingConfigStatics *image_processingConfig::__get_statics__()
  {
    const static image_processingConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = image_processingConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __IMAGE_PROCESSINGRECONFIGURATOR_H__
